---
title: "Homework 4- Regular Expressions"
author: "Morgan Southgate"
date: "February 8, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


##Problem 1
```
Given: 
First String    Second      1.22      3.4
Second          More Text   1.555555  2.2220
Third           x           3         124

Output: 
First String,Second,1.2,3.4
Second,More Tex,1.55555,2.2220
Third,x3,124

Find: \t+
Replace: ,
```
Finds one or more consecutive tab spaces and replaces them with a comma. 


## Problem 2

```
Given:
Ballif, Bryan, University of Vermont
Ellison, Aaron, Harvard Forest
Record, Sydne, Bryn Mawr

Output:
Bryan Ballif (University of Vermont)
Aaron Ellison (Harvard Forest)
Sydne Record (Bryn Mawr)

Find: (\w+),\s*( \w+),\s* (\w+.*)
Replace: \2 \1 [(\3)]

```
Finds one or more consecutive word characters followed by a period and then 0 or more spaces and then a second group of one or more consecutive word characters followed by a period and one or more spaces followed by a third group of non-consecutive word characters. 

Replaces this original string with one in which the output is changed, so that string 2 as delimited by parentheses is first in line, number 1 is second, and number 3 remains third.  

```
Find: ^\w+,\s*\w+,\s*(\w+\s*)+$
replace: \2 \1 (\3)
```

#Problem 3

```
Given: 
0001 Georgia Horseshoe.mp3 0002 Billy In The Lowground.mp3 003 Cherokee Shuffle.mp3 0004 Walking Cane.mp3

1. Output:
0001 Georgia Horseshoe.mp3
0002 Billy In The Lowground.mp3
0003 Cherokee Shuffle.mp3
0004 Walking Cane.mp3

Find: \s*(\d{3,5})
Replace: \n\1

```
Finds zero or more spaces followed by three to five digits, and these number characters are encircled by parentheses for use in replace section. 

This string is replaced by a new line on which is the first (only) element indicated by the parentheses.

```
2. Output:
Georgia Horseshoe_0001.mp3
Billy In The Lowground_0002.mp3
Cherokee Shuffle_0003.mp3
Walking Cane_0004.mp3

FIND: ^(\d+)\s+((\w+\s*+)+)(.mp3)$
REPLACE: \2_\1\4
```
Finds the beginning of a line followed by one or more digits indicated by parentheses as an element, followed by one or more spaces, and then the name of the song, indicating the possibility of more than one word and more than one space with double parentheses. These also serve to make the name of the song the second element indicated. .mp3 is the last element, followed by a $ sign to denote the end of the string.  

This string is replaced by a new string in which the second element appears first, followed by an underscore and then the first element and then the fourth element. 


# Problem 4

```
Given:
Camponotus,pennsylvanicus,10.2,44
Camponotus,herculeanus,10.5,3
Myrmica,punctiventris,12.2,4
Lasius,neoniger,3.3,55

1. Output:
C_pennsylvanicus,44
C_herculeanus,3
M_punctiventris,4
L_neoniger,55

Find: (\w)\w+,\s*(\w+),\d+.\d,(\d+)
Replace: \1_\2,\3
```
Finds one word character and marks it with parentheses and then one or more word characters within the same string, then 0 or more spaces (in case there are errors in the code) followed by 1 or more word characters marked as the second string with parentheses. This is followed by a comma and then 1 or more number characters followed by a period, one number character followed by a comma, and then marked as the third string containing 1 or more number characters.

Replaces original structure with the first element in parenthese followed by an underscore, and then the second marked element followed by a comma and then element 3. 

```
2. Output:
C_penn,44
C_herc,3
M_punc,4
L_neon,55

Find: (\w)_(\w{4})\w+,(\d+)
Replace: \1_\2,\3

```
Finds the first word character and marks it with parentheses for the capital letter standing for the first letter in the genus name. This is followed by an underscore and then marking of the second element with parentheses which include four word characters in a row, followed by one or more word characters and then a comma, and then one or more digit characters is the third element indicated by parentheses. 

Replaces the above structure with the first marked element and then an underscore followed by the second marked element, a comma, and then the third marked element. 

    
  

